import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body className="min-h-screen flex flex-col">
          {/* Navbar */}
          {/* <Navbar /> */}

          {/* Main content */}
          <main className="flex-grow">{children}</main>

          {/* Footer */}
          {/* <Footer /> */}
        </body>
      </html>
    </>
  );
}

// src/app/layout.js
// import Navbar from './components/Navbar';
// import Footer from './components/Footer';
// import './globals.css';
